// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	message "github.com/mateusmacedo/go-ether-sdk/test/fixture/blog/application/message"
	mock "github.com/stretchr/testify/mock"
)

// RegisterAuthorOption is an autogenerated mock type for the RegisterAuthorOption type
type RegisterAuthorOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RegisterAuthorOption) Execute(_a0 *message.RegisterAuthorMessage) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*message.RegisterAuthorMessage) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRegisterAuthorOption creates a new instance of RegisterAuthorOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterAuthorOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterAuthorOption {
	mock := &RegisterAuthorOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
