// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	model "github.com/mateusmacedo/go-ether-sdk/test/fixture/blog/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// RegisterNewAuthorService is an autogenerated mock type for the RegisterNewAuthorService type
type RegisterNewAuthorService struct {
	mock.Mock
}

// RegisterNewAuthor provides a mock function with given fields: author
func (_m *RegisterNewAuthorService) RegisterNewAuthor(author *model.Author) error {
	ret := _m.Called(author)

	if len(ret) == 0 {
		panic("no return value specified for RegisterNewAuthor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Author) error); ok {
		r0 = rf(author)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRegisterNewAuthorService creates a new instance of RegisterNewAuthorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterNewAuthorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterNewAuthorService {
	mock := &RegisterNewAuthorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
